name: Main CI

on: push

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Run Linter
        run:  npm run lint

      - name: Run Typecheck
        run: npm run typecheck

      - name: Run Tests
        run: npm test
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
